### ISSUE TITLE
Possible to have an empty tag at the end

### ISSUE THREAD

**Issue by myobie** [jamesgolick/is_taggable#1]
With a tags string like "one, two, three, " it will parse out as a list array of ["one", "two", "three", ""]. This causes activerecord validation errors.

**Comment by myobie** [comment]
Here is a patch (with test) to fix the issue. Simply reject all blank array elements.

http://gist.github.com/111750

**Comment by danielharan** [comment]
can you fork and apply to your branch? thanks!

**Comment by myobie** [comment]
See here: http://github.com/myobie/is_taggable/tree/master

I just edited it online in github since it's simple. Please run the tests just to make sure.

**Comment by danielharan** [comment]
thanks myobie; I just pulled both the test and the change.
