### ISSUE TITLE
In is_taggable.rb joining not by delimeter

### ISSUE THREAD

**Issue by cypok** [jamesgolick/is_taggable#3]
Why you split by delimeter and join only with ", "?

**Comment by jamesgolick** [comment]
Sounds like a bug. If you'd like to submit a patch, I'd be happy to apply it.

**Comment by rrouse** [comment]
I did a quick patch. One minor change to a test (deletion of the extra space because of the previous join call in question). All tests still pass.

Robert

**Comment by cypok** [comment]
But it's not a good idea to join them without space... Any ideas?

**Comment by jamesgolick** [comment]
This is solved by IronDigital. You can gsub(/,/, ', ') if you want the space to be there in a list that you're presenting to a user.
